# generated by datamodel-codegen:
#   filename:  GoCardless Bank Account Data API (v2).json
#   timestamp: 2024-11-15T17:19:56+00:00

# from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Annotated, Any, Optional
from uuid import UUID

from pydantic import AnyUrl, Field, conint, constr, field_validator

from nordigen_cli.models.mixins import BaseRootMixin


class Account(BaseRootMixin):
    """
    AccountSerializer.
    """

    id: Optional[UUID] = Field(
        None,
        description="The ID of this Account, used to refer to this account in other API calls.",
    )
    created: Optional[datetime] = Field(
        None,
        description="The date & time at which the account object was created.",
    )
    last_accessed: Optional[datetime] = Field(
        None,
        description="The date & time at which the account object was last accessed.",
    )
    iban: Optional[str] = Field(None, description="The Account IBAN")
    bban: Optional[str] = Field(None, description="The Account BBAN")
    status: Optional[str] = Field(
        None, description="The processing status of this account."
    )
    institution_id: Optional[str] = Field(
        None, description="The ASPSP associated with this account."
    )
    owner_name: Optional[str] = Field(
        None, description="The name of the account owner."
    )


class AccountSchema(BaseRootMixin):
    """
    AccountSchema.
    """

    iban: Optional[str] = Field(None, description="iban")
    bban: Optional[str] = Field(None, description="bban")
    pan: Optional[str] = Field(None, description="pan")
    maskedPan: Optional[str] = Field(None, description="maskedPan")
    msisdn: Optional[str] = Field(None, description="msisdn")
    currency: Optional[str] = Field(None, description="currency")


class BalanceAmountSchema(BaseRootMixin):
    """
    BalanceAmountSchema.
    """

    amount: str = Field(..., description="amount")
    currency: str = Field(..., description="currency")


class BalanceSchema(BaseRootMixin):
    """
    BalanceSchema.
    """

    balanceAmount: BalanceAmountSchema = Field(..., description="balanceAmount")
    balanceType: str = Field(..., description="balanceType")
    creditLimitIncluded: Optional[bool] = Field(None, description="creditLimitIncluded")
    lastChangeDateTime: Optional[str] = Field(None, description="lastChangeDateTime")
    referenceDate: Optional[str] = Field(None, description="referenceDate")
    lastCommittedTransaction: Optional[str] = Field(
        None, description="lastCommittedTransaction"
    )


class CurrencyExchangeSchema(BaseRootMixin):
    """
    CurrencyExchangeSchema.
    """

    sourceCurrency: Optional[str] = Field(None, description="sourceCurrency")
    exchangeRate: Optional[str] = Field(None, description="exchangeRate")
    unitCurrency: Optional[str] = Field(None, description="unitCurrency")
    targetCurrency: Optional[str] = Field(None, description="targetCurrency")
    quotationDate: Optional[str] = Field(None, description="quotationDate")
    contractIdentification: Optional[str] = Field(
        None, description="contractIdentification"
    )


class EndUserAgreement(BaseRootMixin):
    """
    Represents an end-user agreement.
    """

    id: Optional[UUID] = Field(
        None,
        description="The ID of this End User Agreement, used to refer to this end user agreement in other API calls.",
        title="End User Agreement ID",
    )
    created: Optional[datetime] = Field(
        None,
        description="The date & time at which the end user agreement was created.",
        title="Created Date",
    )
    institution_id: str = Field(..., description="an Institution ID for this EUA")
    max_historical_days: Optional[conint(ge=1, le=730)] = Field(
        90,
        description="Maximum number of days of transaction data to retrieve.",
        title="Maximum Historical Days",
    )
    access_valid_for_days: Optional[conint(ge=1, le=180)] = Field(
        90,
        description="Number of days from acceptance that the access can be used.",
        title="Access Valid For (Days)",
    )
    access_scope: Annotated[
        Optional[list[str]],
        Field(
            default_factory=lambda: ["balances", "details", "transactions"],
            description="Array containing one or several values of ['balances', 'details', 'transactions']",
            title="Level of information to access (by default all)",
        ),
    ]
    accepted: Optional[datetime] = Field(
        None,
        description="The date & time at which the end user accepted the agreement.",
        title="Accepted Date",
    )


class EndUserAgreementRequest(BaseRootMixin):
    """
    Represents an end-user agreement.
    """

    institution_id: constr(min_length=1) = Field(
        ..., description="an Institution ID for this EUA"
    )
    max_historical_days: Optional[conint(ge=1, le=730)] = Field(
        90,
        description="Maximum number of days of transaction data to retrieve.",
        title="Maximum Historical Days",
    )
    access_valid_for_days: Optional[conint(ge=1, le=180)] = Field(
        90,
        description="Number of days from acceptance that the access can be used.",
        title="Access Valid For (Days)",
    )
    access_scope: Annotated[
        Optional[list],
        Field(
            ["balances", "details", "transactions"],
            description="Array containing one or several values of ['balances', 'details', 'transactions']",
            title="Level of information to access (by default all)",
        ),
    ]


class EnduserAcceptanceDetailsRequest(BaseRootMixin):
    """
    Represents end-user details.
    """

    user_agent: constr(min_length=1) = Field(
        ..., title="user agent string for the end user"
    )
    ip_address: constr(min_length=1) = Field(..., title="end user IP address")


class ErrorResponse(BaseRootMixin):
    summary: str
    detail: str
    type: Optional[str] = None
    status_code: int


class Integration(BaseRootMixin):
    """
    Represents an Integration.
    """

    id: str
    name: str
    bic: Optional[str] = None
    transaction_total_days: Optional[str] = "90"
    max_access_valid_for_days: Optional[str] = "180"
    countries: list[str]
    logo: str


class IntegrationRetrieve(BaseRootMixin):
    """
    IntegrationSerializer for Retrieve endpoint.
    """

    id: str
    name: str
    bic: Optional[str] = None
    transaction_total_days: Optional[str] = "90"
    max_access_valid_for_days: Optional[str] = None
    countries: list[str]
    logo: str
    supported_payments: dict[str, Any]
    supported_features: list
    identification_codes: list


class JWTObtainPairRequest(BaseRootMixin):
    """
    Obtain JWT pair.
    """

    secret_id: constr(min_length=1) = Field(
        ...,
        description="Secret id from /user-secrets/",
    )
    secret_key: constr(min_length=1) = Field(
        ...,
        description="Secret key from /user-secrets/",
    )


class JWTRefreshRequest(BaseRootMixin):
    """
    Refresh access token.
    """

    refresh: constr(min_length=1)


class OwnerAddressStructuredSchema(BaseRootMixin):
    """
    OwnerAddressStructuredSchema.
    """

    streetName: Optional[str] = Field(None, description="streetName")
    buildingNumber: Optional[str] = Field(None, description="buildingNumber")
    townName: Optional[str] = Field(None, description="townName")
    postCode: Optional[str] = Field(None, description="postCode")
    country: Optional[str] = Field(None, description="country")


class PaginatedEndUserAgreementList(BaseRootMixin):
    count: int = Field(...)
    next: Optional[AnyUrl] = Field(
        None,
    )
    previous: Optional[AnyUrl] = Field(
        None,
    )
    results: list[EndUserAgreement]


class RequisitionRequest(BaseRootMixin):
    """
    RequisitionSerializer.
    """

    redirect: AnyUrl = Field(
        ...,
        description="redirect URL to your application after end-user authorization with ASPSP",
    )
    institution_id: constr(min_length=1) = Field(
        ..., description="an Institution ID for this Requisition"
    )
    agreement: Optional[UUID] = Field(
        None, description="EUA associated with this requisition"
    )
    reference: Optional[constr(min_length=1, max_length=256)] = Field(
        None, description="additional ID to identify the end user"
    )
    user_language: Optional[constr(min_length=1, max_length=5)] = Field(
        None, description="A two-letter country code (ISO 639-1)"
    )
    ssn: Optional[constr(max_length=64)] = Field(
        None,
        description="optional SSN field to verify ownership of the account",
    )
    account_selection: Optional[bool] = Field(
        False,
        description="option to enable account selection view for the end user",
    )
    redirect_immediate: Optional[bool] = Field(
        False,
        description="enable redirect back to the client after account list received",
    )


class SpectacularJWTObtain(BaseRootMixin):
    """
    Obtain new JWT pair.
    """

    access: Annotated[Optional[str], Field(None, description="Your access token")]
    access_expires: Annotated[
        Optional[int],
        Field(86400, description="Access token expires in seconds"),
    ]
    refresh: Annotated[Optional[str], Field(None, description="Your refresh token")]
    refresh_expires: Optional[int] = Field(
        2592000, description="Refresh token expires in seconds"
    )


class SpectacularJWTRefresh(BaseRootMixin):
    """
    Refresh Access token.
    """

    access: Optional[str] = Field(None, description="Your access token")
    access_expires: Optional[int] = Field(
        86400, description="Access token expires in seconds"
    )


class StatusEnum(Enum):
    CR = "CR"
    ID = "ID"
    LN = "LN"
    RJ = "RJ"
    ER = "ER"
    SU = "SU"
    EX = "EX"
    GC = "GC"
    UA = "UA"
    GA = "GA"
    SA = "SA"


class TransactionAmountSchema(BaseRootMixin):
    """
    TransactionAmountSchema.
    """

    amount: str = Field(..., description="amount")
    currency: str = Field(..., description="currency")


class TransactionSchema(BaseRootMixin):
    """
    TransactionSchema.
    """

    transactionId: Optional[str] = Field(None, description="transactionId")
    entryReference: Optional[str] = Field(None, description="entryReference")
    endToEndId: Optional[str] = Field(None, description="endToEndId")
    mandateId: Optional[str] = Field(None, description="mandateId")
    checkId: Optional[str] = Field(None, description="checkId")
    creditorId: Optional[str] = Field(None, description="creditorId")
    bookingDate: Optional[str] = Field(None, description="bookingDate")
    valueDate: Optional[str] = Field(None, description="valueDate")
    bookingDateTime: Optional[str] = Field(None, description="bookingDateTime")
    valueDateTime: Optional[str] = Field(None, description="valueDateTime")
    transactionAmount: Annotated[
        TransactionAmountSchema, Field(..., description="transactionAmount")
    ]
    currencyExchange: Optional[list[CurrencyExchangeSchema]] = None
    creditorName: Optional[str] = Field(None, description="creditorName")
    creditorAccount: Optional[AccountSchema] = Field(
        None, description="creditorAccount"
    )
    ultimateCreditor: Optional[str] = Field(None, description="ultimateCreditor")
    debtorName: Optional[str] = Field(None, description="debtorName")
    debtorAccount: Optional[AccountSchema] = Field(None, description="debtorAccount")
    ultimateDebtor: Optional[str] = Field(None, description="ultimateDebtor")
    remittanceInformationUnstructured: Optional[str] = Field(
        None, description="remittanceInformationUnstructured"
    )
    remittanceInformationUnstructuredArray: Optional[list[str]] = Field(
        None, description="remittanceInformationUnstructuredArray"
    )
    remittanceInformationStructured: Optional[str] = Field(
        None, description="remittanceInformationStructured"
    )
    remittanceInformationStructuredArray: Optional[list[str]] = Field(
        None, description="remittanceInformationStructuredArray"
    )
    additionalInformation: Optional[str] = Field(
        None, description="additionalInformation"
    )
    purposeCode: Optional[str] = Field(None, description="purposeCode")
    bankTransactionCode: Optional[str] = Field(None, description="bankTransactionCode")
    proprietaryBankTransactionCode: Optional[str] = Field(
        None, description="proprietaryBankTransactionCode"
    )
    internalTransactionId: Optional[str] = Field(
        None, description="internalTransactionId"
    )


class AccountBalance(BaseRootMixin):
    """
    AccountBalanceSerializer.
    """

    balances: Optional[list[BalanceSchema]] = None


class BankTransaction(BaseRootMixin):
    """
    BankTransactionSerializer.
    """

    booked: list[TransactionSchema]
    pending: Optional[list[TransactionSchema]] = None


class DetailSchema(BaseRootMixin):
    """
    DetailSchema.
    """

    resourceId: Optional[str] = Field(None, description="resourceId")
    iban: Optional[str] = Field(None, description="iban")
    bban: Optional[str] = Field(None, description="bban")
    scan: Optional[str] = Field(
        None,
        description="SortCodeAccountNumber returned by some UK banks "
        "(6 digit Sort Code and 8 digit Account Number)",
    )
    msisdn: Optional[str] = Field(None, description="msisdn")
    currency: Optional[str] = Field(None, description="currency")
    ownerName: Optional[str] = Field(None, description="ownerName")
    name: Optional[str] = Field(None, description="name")
    displayName: Optional[str] = Field(None, description="displayName")
    product: Optional[str] = Field(None, description="product")
    cashAccountType: Optional[str] = Field(None, description="cashAccountType")
    status: Optional[str] = Field(None, description="status")
    bic: Optional[str] = Field(None, description="bic")
    linkedAccounts: Optional[str] = Field(None, description="linkedAccounts")
    maskedPan: Optional[str] = Field(None, description="maskedPan")
    usage: Optional[str] = Field(None, description="usage")
    details: Optional[str] = Field(None, description="details")
    ownerAddressUnstructured: Optional[list[str]] = Field(
        None, description="ownerAddressUnstructured"
    )
    ownerAddressStructured: Optional[OwnerAddressStructuredSchema] = Field(
        None, description="ownerAddressStructured"
    )


class Requisition(BaseRootMixin):
    """
    RequisitionSerializer.
    """

    id: Optional[UUID] = None
    created: Optional[datetime] = Field(
        None,
        description="The date & time at which the requisition was created.",
        title="Created Date",
    )
    redirect: AnyUrl = Field(
        ...,
        description="redirect URL to your application after end-user"
        "authorization with ASPSP",
    )
    status: Optional[StatusEnum] = Field(
        None,
        description="status of this requisition",
        title="Requisition status",
    )
    # modified as API returns None for some cases
    institution_id: Optional[str] = Field(
        ..., description="an Institution ID for this Requisition"
    )

    @field_validator("agreement", mode="before")
    @classmethod
    def validate_empty_agreement(cls, value):
        if value == "":
            return None
        return value

    # modified as API returns empty string for some cases
    agreement: Optional[UUID] = Field(
        None, description="EUA associated with this requisition"
    )
    reference: Optional[constr(max_length=256)] = Field(
        None, description="additional ID to identify the end user"
    )
    accounts: Optional[list[UUID]] = Field(
        None,
        description="array of account IDs retrieved within a scope of this requisition",
    )
    user_language: Optional[constr(max_length=5)] = Field(
        None, description="A two-letter country code (ISO 639-1)"
    )

    @field_validator("link", mode="before")
    @classmethod
    def validate_empty_link(cls, value):
        if value == "":
            return None
        return value

    # modified as API returns empty string for some cases
    link: Optional[AnyUrl] = Field(
        "https://ob.gocardless.com/psd2/start/3fa85f64-5717-4562-b3fc-2c963f66afa6/{$INSTITUTION_ID}",
        description="link to initiate authorization with Institution",
    )
    ssn: Optional[constr(max_length=64)] = Field(
        None,
        description="optional SSN field to verify ownership of the account",
    )
    account_selection: Optional[bool] = Field(
        False,
        description="option to enable account selection view for the end user",
    )
    redirect_immediate: Optional[bool] = Field(
        False,
        description="enable redirect back to the client after account list received",
    )


class SpectacularRequisition(BaseRootMixin):
    """
    Create requisition.
    """

    id: Optional[UUID] = None
    created: Optional[datetime] = Field(
        None,
        description="The date & time at which the requisition was created.",
        title="Created Date",
    )
    redirect: AnyUrl = Field(
        ...,
        description="redirect URL to your application after end-user"
        "authorization with ASPSP",
    )
    status: Optional[StatusEnum] = Field(
        None,
        description="status of this requisition",
        title="Requisition status",
    )
    institution_id: str = Field(
        ..., description="an Institution ID for this Requisition"
    )
    agreement: Optional[UUID] = Field(
        None, description="EUA associated with this requisition"
    )
    reference: Optional[constr(max_length=256)] = Field(
        None, description="additional ID to identify the end user"
    )
    accounts: Annotated[
        Optional[list[UUID]],
        Field(
            default_factory=list,
            description="array of account IDs retrieved within a"
            "scope of this requisition",
        ),
    ]
    user_language: Optional[constr(max_length=5)] = Field(
        None, description="A two-letter country code (ISO 639-1)"
    )
    link: Optional[AnyUrl] = Field(
        "https://ob.gocardless.com/psd2/start/3fa85f64-5717-4562-b3fc-2c963f66afa6/{$INSTITUTION_ID}",
        description="link to initiate authorization with Institution",
    )
    ssn: Optional[constr(max_length=64)] = Field(
        None,
        description="optional SSN field to verify ownership of the account",
    )
    account_selection: Optional[bool] = Field(
        False,
        description="option to enable account selection view for the end user",
    )
    redirect_immediate: Optional[bool] = Field(
        False,
        description="enable redirect back to the client after account list received",
    )


class AccountDetail(BaseRootMixin):
    """
    AccountDetailSerializer.
    """

    account: DetailSchema = Field(..., description="account")


class AccountTransactions(BaseRootMixin):
    """
    AccountTransactionsSerializer.
    """

    transactions: BankTransaction = Field(..., description="transactions")


class PaginatedRequisitionList(BaseRootMixin):
    count: int = Field(...)
    next: Optional[AnyUrl] = Field(
        None,
    )
    previous: Optional[AnyUrl] = Field(
        None,
    )
    results: list[Requisition]


# print(models)

# example that was auto-generated by datamodel-codegen:
# class PaginatedRequisitionList(BaseRootMixin):
#     count: int = Field(...)
#     next: Optional[AnyUrl] = Field(
#         None,
#         example="https://bankaccountdata.gocardless.com/api/v2/requisitions/?limit=100&offset=0",
#     )
#     previous: Optional[AnyUrl] = Field(
#         None,
#         example="https://bankaccountdata.gocardless.com/api/v2/requisitions/?limit=100&offset=0",
#     )
#     results: List[Requisition]
