[pytest]
addopts = '-rP'
python_files = tests.py test_*.py *_tests.py
norecursedirs = .venv .vscode .idea local .claudesync venv node_modules
filterwarnings =
    ignore::DeprecationWarning:coreapi.*:
    ignore::DeprecationWarning:pkg_resources.*:
    ignore::DeprecationWarning:rest_framework.*:
    ignore::DeprecationWarning:reportlab.*:

