[tox]
envlist = py312
isolated_build = True

;[testenv:lint]
;description = run linter
;skip_install = true
;deps =
;     -r requirements-dev.txt
;commands = ruff {posargs:src tests}
;
;[testenv:type]
;description = run type checks
;commands =
;    mypy {posargs:src tests}

[testenv]
description = Run the pytests!
allowlist_externals = poetry
deps = pytest
# commands_pre =  poetry install --no-root
commands =
  poetry install --no-root
  poetry run pytest {posargs:tests}

